### POST

POST  http://localhost:3000/user-api/user
Content-Type: application/json

{
    "name":"arjun",
    "email":"arjun@gmail.com",
    "DOB":"10-10-2005",
    "mobilenumber":9515102215
}
###
POST  http://localhost:3000/user-api/user
Content-Type: application/json

{
    "name":"karthik",
    "email":"karthik@gmail.com",
    "DOB":"09-07-2007",
    "mobilenumber":950000000
}
###
POST  http://localhost:3000/user-api/user
Content-Type: application/json

{
    "name":"karthik09",
    "email":"23eg112e61gmail.com",
    "DOB":"09-07-2003",
    "mobilenumber":9500000
}
###
GET http://localhost:3000/user-api/users


### get user by ID
GET http://localhost:3000/user-api/users/69a6945a8d11d2dd1de0bb16



### delete the user by ID 

DELETE http://localhost:3000/user-api/users/69a6945a8d11d2dd1de0bb16

### patch the user by Id (activate the user by the id)
PATCH  http://localhost:3000/user-api/users/69a6945a8d11d2dd1de0bb16